<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Wechat\Module'                        => __DIR__ . '/Module.php',
    'Wechat\Controller\IndexController' => __DIR__ . '/src/Wechat/Controller/IndexController.php',
    'WechatTest\Framework\TestCase'        => __DIR__ . '/tests/Wechat/Framework/TestCase.php',
    'WechatTest\SampleTest'                => __DIR__ . '/tests/Wechat/SampleTest.php',
);
