<!DOCTYPE html>
<html lang="ZH">
<head>
<title>Our Love Story</title>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=670px" />
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/love/garden.js"></script>
<script type="text/javascript" src="/love/functions.js"></script>
<link href="/love/style.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" href="/love/reset.css" />
<style type="text/css">
@font-face {
	font-family: digit;
	src: url('digital-7_mono.ttf') format("truetype");
}
</style>
</head>
<body>
	<?php echo $this->content; ?>
</body>
</html>
