<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

        <!-- Le styles -->
        <?php 
								
								echo $this->headLink ( array (
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/img/favicon.ico' 
								) )?>
		<link rel="stylesheet" href="/jquery-ui-themes/themes/black-tie/jquery-ui.min.css">
		<link type="text/css" rel="stylesheet" href="/css/content_style.css">
        <!-- Scripts -->
        <script src="/js/jquery-1.7.2.min.js"></script>
        <script src="/js/jquery-ui.min.js"></script>
        <script src="/js/cly.js"></script>
    </head>
<body>
	<div class="container">
            <?php echo $this->content; ?>
	</div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>
