<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('微信公众平台管理系统'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

        <!-- Le styles -->
        <?php
								
								echo $this->headLink ( array (
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/img/favicon.ico' 
								) )->prependStylesheet ( $this->basePath () . '/css/menu/admin.css' )->prependStylesheet ( $this->basePath () . '/css/menu/navtab.css' )?>
        <!-- Scripts -->
        <?php
								
								echo $this->headScript ()->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) )->prependFile ( $this->basePath () . '/js/menu/global.js' )->prependFile ( $this->basePath () . '/js/menu/navtab.js' )->prependFile ( $this->basePath () . '/js/jquery.min.js' )?>

    </head>
<body>
	<?php echo $this->content; ?>
</body>
</html>
