<script type="text/javascript">
<!--
$(function(){
	$(".jsAdd").click(function(){
		
	});
});
//-->
</script>
<div class="codeAdd">
	<form method="post" action="<?php echo $this->addUrl?>">
		<label>场景值</label> <input name="sceneId" class="sceneId"
			placeholder="请输入1-100000之内的整数" /> <label>备注</label> <input
			name="note" /> <input class="jsAdd" type="submit" value="添加" />
	</form>
</div>
<div class="codeList">
	<div class="codeBar">
		<p class="title code">二维码</p>
		<p class="title sceneId">场景值</p>
		<p class="title note">注释</p>
		<p class="title active">访问次数</p>
		<p class="title operate">操作</p>
	</div>
	<ul>
	   <?php foreach ($this->paginator as $item): ?>
	   <?php
					$sceneId = $item ['sceneId'];
					$note = $item ['note'];
					$cid = $item ['cid'];
					$sqlStr = "select sum(active) as active from wc_code_active where cid=$cid";
					$active = $this->service->getDb ()->queryExecute ( $sqlStr )->current ()['active'];
					?>
		<li>
			<p class="code">
				<img alt="<?php echo 'sceneId='.$sceneId?>"
					src="<?php
					echo Cly\Common\ClyLib::addQuery ( $this->baseUri, array (
							'action' => 'show',
							sceneId => $sceneId 
					) );
					?>">
			</p>
			<p class="sceneId"><?php echo $sceneId?></p>
			<p class="note"><?php echo $note?></p>
			<p class="active"><?php echo $active?></p>
			<p class="operate">
				<a
					href="<?php
					echo Cly\Common\ClyLib::addQuery ( $this->baseUri, array (
							'action' => 'delete',
							sceneId => $sceneId 
					) );
					?>">删除</a>
			</p>
		</li>
		<?php endforeach;?>
	</ul>
</div>
<?php
echo $this->paginationControl ( $this->paginator, 'Sliding', 'wechat/paginator', array (
		'baseUri' => $this->baseUri 
) );
?>
