<!DOCTYPE html>
<html lang="ZH">
<head>
<meta charset="gb2312" />
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"/>
<meta http-equiv="keywords" content="七夕,表白" />
<meta http-equiv="description" content="大声把你的爱对TA说出来吧" />
<title>七夕我要对TA说</title>
<link rel="stylesheet" href="/love/reset.css"/>
</head>

<body style="background:#fff;">
<a class="back" href="<?php echo $this->indexUrl?>">返回</a>
<h2>我发送的</h2>
<div class="list">
	<ul>
    	<li>
        	<a href="#">
       		<b>我</b><span>发送给</span><b>1860789546</b>
            <p>我陷入深深的睡眠，明月却依旧悬挂在心空；即使你没有出现在我的门前，我也不会让它下山；这个冬天不太冷，加厚的棉衣裹不住我的透明的思恋</p>
            </a>
        </li>
		<li>
        	<a href="#">
       		<b>我</b><span>发送给</span><b>1860789546</b>
            <p>我陷入深深的睡眠，明月却依旧悬挂在心空；即使你没有出现在我的门前，我也不会让它下山；这个冬天不太冷，加厚的棉衣裹不住我的透明的思恋</p>
            </a>
        </li>
        <li>
        	<a href="#">
       		<b>我</b><span>发送给</span><b>1860789546</b>
            <p>我陷入深深的睡眠，明月却依旧悬挂在心空；即使你没有出现在我的门前，我也不会让它下山；这个冬天不太冷，加厚的棉衣裹不住我的透明的思恋</p>
            </a>
        </li>
    </ul>
</div>


</div>
</body>
</html>